# Generated by Django 4.2.2 on 2023-10-25 13:25

from django.db import migrations
import django_resized.forms
import maaps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0041_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=90, scale=None, size=[1920, 1280], upload_to=maaps.models.rename_file),
        ),
    ]
