services:
 server:
    image: ghcr.io/ztl-space/maaps:main
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./data/media:/server/media
      - db:/server/db
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
    db: